### ISSUE TITLE
[feature request] Release version 1.0

### ISSUE THREAD

**Issue by xyproto** [felixge/go-xxd#4]
Hi,

I'm making an unofficial Arch Linux package for go-xxd.

Could you please add a git tag for a release, like `1.0` and also add a license file, just to make it easier to package?

Best regards,
Alexander Rødseth

**Comment by felixge** [comment]
@xyproto hm, I could slap an MIT license on it, but the truth is, the IP of this repo is a bit muddy. The original code was taken from an [reddit post](https://www.reddit.com/r/golang/comments/2s1zn1/how_can_i_improve_the_performance_of_my_xxd_port/) that had no license on it. I think at this point there isn't anything left of the original code, so I guess I'd be okay with ignoring it. However, @ericlagergren made significant contributions to this package, so I'd need his okay before adding a license. @ericlagergren would MIT be okay with you?

**Comment by ericlagergren** [comment]
Yup!

**Comment by felixge** [comment]
Added a license and tagged the commit as v1.0.0. See https://github.com/felixge/go-xxd/commit/bf26abc251c49909b596e7fc59d95f759a308480
